# Generated by Django 4.2.6 on 2023-11-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='video_link',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='portfolio/projects/'),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='portfolio/')),
                ('big_title', models.CharField(max_length=100)),
                ('projects', models.ManyToManyField(to='portfolio.project')),
            ],
        ),
    ]
