# Generated by Django 4.2.6 on 2023-11-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_project_video_link_project_image_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='job',
        ),
    ]
