# Generated by Django 4.2.6 on 2023-11-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_github_link_portfolio_linkedin_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='github_link',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='linkedin_link',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='twitter_link',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='youtube_link',
            new_name='youtube',
        ),
    ]
