# Generated by Django 4.2.6 on 2023-11-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_github_link_portfolio_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
