# Generated by Django 4.2.6 on 2023-11-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_portfolio_picture_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='email',
            field=models.URLField(blank=True, null=True),
        ),
    ]
