# Generated by Django 4.2.6 on 2023-11-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_portfolio_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='about',
            field=models.TextField(default='Write about yourself'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='about_img',
            field=models.ImageField(default='default.jpg', upload_to='media/portfolio'),
        ),
    ]
