# Generated by Django 4.2.6 on 2023-11-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_remove_projectdetail_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='live_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
